### ISSUE TITLE
Use variable width for breadcrumbs

### ISSUE THREAD

**Issue by fbreitwieser** [AntoineGuillot2/D3partitionR#1]
First, thanks for these great visualizations! 

I have data with sometimes long category names which leads to overwriting in the breadcrumbs trail.

![image](https://user-images.githubusercontent.com/516060/27512131-ab106b92-5904-11e7-8b33-441ed2c69f48.png)

Can you adapt the breadcrumb sizes to the string length?

**Comment by AntoineGuillot2** [comment]
Hi, this is corrected in the last version
