### ISSUE TITLE
Include data

### ISSUE THREAD

**Issue by csgillespie** [AntoineGuillot2/D3partitionR#10]
It would be nicer if we could get the data set easier, e.g.
```
titanic_data=fread("train.csv")
```
Won't work without getting `train.csv` and most users are lazy ;)

Could you use https://cran.r-project.org/web/packages/titanic/ in your example instead?

**Comment by AntoineGuillot2** [comment]
Yes, you are right, it will be easier to do so. I'll include some dataset in the next version.
