### ISSUE TITLE
How to disable the black borders?

### ISSUE THREAD

**Issue by ningzhibin** [AntoineGuillot2/D3partitionR#16]
I saw a demo of previous versions ( 0.1, 0.3) do not have black borders.
How can I disable the black borders in current version?

**Comment by edmundex** [comment]
I don't see if there is an option in the R functions to customize the node's CSS. As a dirty trick, you could fork the repo, change the black stroke to white in D3partitionR/inst/htmlwidgets/js/plot_d3partitionR.js, and then install your forked repo with install_github. Please let me know if there is a better way to do this.

Would be nice if we can customize the node CSS like tooltip's function.

**Comment by AntoineGuillot2** [comment]
Hello, it was not possible to change the CSS properties of the nodes. I added a 'set_nodes_style' function which does so on the dev branch. This function is experimental, your feedbacks are welcomes.
Best regards,
Antoine
