### ISSUE TITLE
Add an option to customise nodes CSS

### ISSUE THREAD

**Issue by AntoineGuillot2** [AntoineGuillot2/D3partitionR#2]
Add a function, for instance, set_nodes_style, to modify the nodes CSS. The function could have two parameters, one to provide the style on hover and the other one to specify the basic CSS style.

**Comment by ningzhibin** [comment]
I saw a demo of previous versions ( 0.1, 0.3) do not have black borders.
How can I disable the black borders in current version?

**Comment by AntoineGuillot2** [comment]
Added in the dev branch
